/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_get_sessionposition_width(a: number): number;
export function __wbg_set_sessionposition_width(a: number, b: number): void;
export function __wbg_get_sessionposition_height(a: number): number;
export function __wbg_set_sessionposition_height(a: number, b: number): void;
export function __wbg_point_free(a: number): void;
export function __wbg_get_point_0(a: number): number;
export function __wbg_set_point_0(a: number, b: number): void;
export function __wbg_get_point_1(a: number): number;
export function __wbg_set_point_1(a: number, b: number): void;
export function __wbg_celldata_free(a: number): void;
export function __wbg_get_celldata_text(a: number, b: number): void;
export function __wbg_set_celldata_text(a: number, b: number, c: number): void;
export function __wbg_get_celldata_color(a: number, b: number): void;
export function __wbg_set_celldata_color(a: number, b: number, c: number): void;
export function __wbg_cellinfo_free(a: number): void;
export function __wbg_get_cellinfo_x(a: number): number;
export function __wbg_set_cellinfo_x(a: number, b: number): void;
export function __wbg_get_cellinfo_y(a: number): number;
export function __wbg_set_cellinfo_y(a: number, b: number): void;
export function __wbg_get_cellinfo_width(a: number): number;
export function __wbg_set_cellinfo_width(a: number, b: number): void;
export function __wbg_get_cellinfo_height(a: number): number;
export function __wbg_set_cellinfo_height(a: number, b: number): void;
export function __wbg_set_sessionposition_x(a: number, b: number): void;
export function __wbg_set_sessionposition_y(a: number, b: number): void;
export function __wbg_set_cellposition_x(a: number, b: number): void;
export function __wbg_set_cellposition_y(a: number, b: number): void;
export function __wbg_set_cellposition_width(a: number, b: number): void;
export function __wbg_set_cellposition_height(a: number, b: number): void;
export function __wbg_get_sessionposition_x(a: number): number;
export function __wbg_get_sessionposition_y(a: number): number;
export function __wbg_get_cellposition_x(a: number): number;
export function __wbg_get_cellposition_y(a: number): number;
export function __wbg_get_cellposition_width(a: number): number;
export function __wbg_get_cellposition_height(a: number): number;
export function __wbg_sessionposition_free(a: number): void;
export function __wbg_cellposition_free(a: number): void;
export function __wbg_sectionmanager_free(a: number): void;
export function __wbg_layermanager_free(a: number): void;
export function __wbg_get_layermanager_section_size(a: number): number;
export function __wbg_set_layermanager_section_size(a: number, b: number): void;
export function __wbg_get_layermanager_total_height(a: number): number;
export function __wbg_set_layermanager_total_height(a: number, b: number): void;
export function __wbg_get_layermanager_total_width(a: number): number;
export function __wbg_set_layermanager_total_width(a: number, b: number): void;
export function layermanager_new(a: number, b: number): number;
export function layermanager_init(a: number): void;
export function layermanager_calc_layer(a: number): void;
export function layermanager_get_cell_indices(a: number, b: number, c: number): void;
export function layermanager_test(a: number, b: number): void;
export function layermanager_get_item(a: number, b: number): number;
export function layermanager_get_cell(a: number, b: number): number;
export function layermanager_to_string(a: number, b: number): void;
export function gen_hello_string(a: number, b: number, c: number): void;
export function __wbg_section_free(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
